from __future__ import annotations

from enum import Enum


class Severity(Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


MEMBER_TYPES = {"INDIVIDUAL", "ORGANIZATION"}
PERSONA_TYPES = {
    "SALARIED_TEACHER",
    "COUNTY_WORKER",
    "SME_OWNER",
    "FARMER_SEASONAL",
    "DIASPORA_SUPPORTED",
    "BODA_BODA_OPERATOR",
    "CHURCH_ORG",
}
KYC_LEVELS = {"MINIMAL", "STANDARD", "ENHANCED", "SIMPLIFIED", "PENDING_REFRESH", "RESTRICTED"}
RISK_SEGMENTS = {"LOW", "MEDIUM", "HIGH", "PEP", "SANCTIONS_RELATED", "WATCHLIST", "UNDER_REVIEW"}

ACCOUNT_OWNER_TYPES = {"MEMBER", "INSTITUTION", "SOURCE", "SINK"}
ACCOUNT_TYPES = {
    "BOSA_DEPOSIT",
    "FOSA_SAVINGS",
    "FOSA_CURRENT",
    "SHARE_CAPITAL",
    "LOAN_ACCOUNT",
    "MPESA_WALLET",
    "AIRTEL_WALLET",
    "SOURCE_ACCOUNT",
    "SINK_ACCOUNT",
}
ACCOUNT_STATUSES = {"ACTIVE", "DORMANT", "FROZEN", "CLOSED", "PENDING_OPEN", "RESTRICTED"}

NODE_TYPES = {"INSTITUTION", "MEMBER", "ACCOUNT", "WALLET", "EMPLOYER", "BRANCH", "AGENT", "DEVICE", "SOURCE", "SINK"}
EDGE_TYPES = {
    "HAS_ACCOUNT",
    "HAS_WALLET",
    "EMPLOYED_BY",
    "USES_DEVICE",
    "USES_AGENT",
    "GUARANTEES",
    "RELATED_TO",
    "INTRODUCED_BY",
    "ATTENDS_CHURCH",
    "OWNS_BUSINESS",
    "TRANSACTS_WITH",
    "SHARES_PHONE",
    "SHARES_DEVICE",
    "INSTITUTION_HAS_BRANCH",
    "ACCOUNT_AT_BRANCH",
    "ACCOUNT_BELONGS_TO_INSTITUTION",
    "EMPLOYER_BELONGS_TO_INSTITUTION",
    "SOURCE_FUNDS_ACCOUNT",
    "ACCOUNT_PAYS_SINK",
}

TXN_TYPES = {
    "SALARY_IN",
    "CHECKOFF_DEPOSIT",
    "CHECKOFF_LOAN_RECOVERY",
    "SHARE_CAPITAL_TOPUP",
    "BOSA_DEP_TOPUP",
    "FOSA_CASH_DEPOSIT",
    "FOSA_CASH_WITHDRAWAL",
    "MPESA_PAYBILL_IN",
    "MPESA_WALLET_TOPUP",
    "MPESA_CASHOUT",
    "PESALINK_IN",
    "PESALINK_OUT",
    "WALLET_P2P_IN",
    "WALLET_P2P_OUT",
    "LOAN_DISBURSEMENT",
    "LOAN_REPAYMENT",
    "INTEREST_ACCRUAL",
    "PENALTY_POST",
    "DIVIDEND_POST",
    "ACCOUNT_REACTIVATION",
    "KYC_REFRESH",
    "SYSTEM_CORRECTION",
    "CHURCH_COLLECTION_IN",
    "BUSINESS_SETTLEMENT_IN",
    "SUPPLIER_PAYMENT_OUT",
    "SCHOOL_FEES_PAYMENT_OUT",
    "HOUSEHOLD_SPEND_OUT",
    "REVERSAL",
}
RAILS = {"SACCO_INTERNAL", "MPESA", "AIRTEL_MONEY", "PESALINK", "EFT", "RTGS", "CASH_BRANCH", "CASH_AGENT", "PAYROLL_CHECKOFF", "REMITTANCE"}
CHANNELS = {"BRANCH", "AGENT", "MOBILE_APP", "USSD", "PAYBILL", "TILL", "BANK_TRANSFER", "PAYROLL_FILE", "SYSTEM"}
COUNTERPARTY_TYPES = {"MEMBER", "CUSTOMER", "MERCHANT", "EMPLOYER", "GOVERNMENT", "BANK", "WALLET_USER", "AGENT", "CHURCH", "SACCO", "EXTERNAL_UNKNOWN", "SOURCE", "SINK"}

TYPOLOGIES = {"STRUCTURING", "RAPID_PASS_THROUGH", "FAKE_AFFORDABILITY_BEFORE_LOAN"}
ALERT_ENTITY_TYPES = {"MEMBER", "ACCOUNT", "TRANSACTION", "EDGE", "PATTERN"}
ALERT_SEVERITIES = {"LOW", "MEDIUM", "HIGH", "CRITICAL"}
ALERT_STAGES = {"PLACEMENT", "LAYERING", "INTEGRATION", "PATTERN_SUMMARY"}
